<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    private const CHART_SLUG = 'body-parts';

    public function up(): void
    {
        $bodyPartsData = [
            [
                'key' => 'part_head',
                'name' => 'Head',
                'marathi' => 'डोके (Doke)',
                'hindi' => 'सिर (Sir)',
                'icon' => '🗣️',
                'category' => 'head',
                'side' => 'left',
                'x' => 50,
                'y' => 11,
                'fact' => 'Protects our brain and holds our face, eyes, ears, nose, and mouth.',
                'audioText' => 'Head',
            ],
            [
                'key' => 'part_hair',
                'name' => 'Hair',
                'marathi' => 'केस (Kes)',
                'hindi' => 'बाल (Baal)',
                'icon' => '💇',
                'category' => 'head',
                'side' => 'left',
                'x' => 50,
                'y' => 5,
                'fact' => 'Grows on top of our head and keeps our head warm and protected.',
                'audioText' => 'Hair',
            ],
            [
                'key' => 'part_forehead',
                'name' => 'Forehead',
                'marathi' => 'कपाळ (Kapaal)',
                'hindi' => 'माथा (Maatha)',
                'icon' => '🧠',
                'category' => 'head',
                'side' => 'right',
                'x' => 50,
                'y' => 13,
                'fact' => 'The smooth area on our face right between our eyebrows and hair.',
                'audioText' => 'Forehead',
            ],
            [
                'key' => 'part_eyes',
                'name' => 'Eyes',
                'marathi' => 'डोळे (Dole)',
                'hindi' => 'आँखें (Aankhein)',
                'icon' => '👀',
                'category' => 'sense',
                'side' => 'left',
                'x' => 46,
                'y' => 16,
                'fact' => 'Sense of Sight: Two eyes help us see shapes, vibrant colors, and books.',
                'audioText' => 'Eyes. Used for seeing.',
            ],
            [
                'key' => 'part_ears',
                'name' => 'Ears',
                'marathi' => 'कान (Kaan)',
                'hindi' => 'कान (Kaan)',
                'icon' => '👂',
                'category' => 'sense',
                'side' => 'right',
                'x' => 38,
                'y' => 18,
                'fact' => 'Sense of Hearing: Two ears allow us to hear music, stories, and friends.',
                'audioText' => 'Ears. Used for listening.',
            ],
            [
                'key' => 'part_nose',
                'name' => 'Nose',
                'marathi' => 'नाक (Naak)',
                'hindi' => 'नाक (Naak)',
                'icon' => '👃',
                'category' => 'sense',
                'side' => 'left',
                'x' => 50,
                'y' => 19,
                'fact' => 'Sense of Smell: Helps us smell fragrant flowers and breathe fresh air.',
                'audioText' => 'Nose. Used for smelling and breathing.',
            ],
            [
                'key' => 'part_mouth',
                'name' => 'Mouth',
                'marathi' => 'तोंड (Tond)',
                'hindi' => 'मुँह (Munh)',
                'icon' => '👄',
                'category' => 'head',
                'side' => 'right',
                'x' => 50,
                'y' => 22,
                'fact' => 'We use our mouth to smile, speak cheerfully, and eat delicious food.',
                'audioText' => 'Mouth',
            ],
            [
                'key' => 'part_teeth',
                'name' => 'Teeth',
                'marathi' => 'दात (Daat)',
                'hindi' => 'दाँत (Daant)',
                'icon' => '🦷',
                'category' => 'head',
                'side' => 'left',
                'x' => 48,
                'y' => 23,
                'fact' => 'Shiny white teeth help us chew and break down nutritious food.',
                'audioText' => 'Teeth',
            ],
            [
                'key' => 'part_tongue',
                'name' => 'Tongue',
                'marathi' => 'जीभ (Jeebh)',
                'hindi' => 'जीभ (Jeebh)',
                'icon' => '👅',
                'category' => 'sense',
                'side' => 'right',
                'x' => 52,
                'y' => 24,
                'fact' => 'Sense of Taste: Tastes sweet mangoes, salty popcorn, and sour lemons.',
                'audioText' => 'Tongue. Used for tasting.',
            ],
            [
                'key' => 'part_neck',
                'name' => 'Neck',
                'marathi' => 'मान (Maan)',
                'hindi' => 'गर्दन (Gardan)',
                'icon' => '🧣',
                'category' => 'upper',
                'side' => 'left',
                'x' => 50,
                'y' => 28,
                'fact' => 'Connects our head to our torso and lets our head turn left and right.',
                'audioText' => 'Neck',
            ],
            [
                'key' => 'part_shoulders',
                'name' => 'Shoulders',
                'marathi' => 'खांदे (Khaande)',
                'hindi' => 'कंधे (Kandhe)',
                'icon' => '💪',
                'category' => 'upper',
                'side' => 'right',
                'x' => 36,
                'y' => 32,
                'fact' => 'Strong joints that carry school backpacks and connect our arms.',
                'audioText' => 'Shoulders',
            ],
            [
                'key' => 'part_chest',
                'name' => 'Chest',
                'marathi' => 'छाती (Chhaati)',
                'hindi' => 'छाती (Chhaati)',
                'icon' => '🫁',
                'category' => 'upper',
                'side' => 'left',
                'x' => 50,
                'y' => 35,
                'fact' => 'Contains our rib cage, which safely guards our heart and lungs.',
                'audioText' => 'Chest',
            ],
            [
                'key' => 'part_stomach',
                'name' => 'Stomach',
                'marathi' => 'पोट (Pot)',
                'hindi' => 'पेट (Pet)',
                'icon' => '🥑',
                'category' => 'upper',
                'side' => 'right',
                'x' => 50,
                'y' => 44,
                'fact' => 'Digests our meals to give our body energy to play and learn.',
                'audioText' => 'Stomach',
            ],
            [
                'key' => 'part_arms',
                'name' => 'Arms',
                'marathi' => 'हात (Haat)',
                'hindi' => 'बाँह (Baanh)',
                'icon' => '💪',
                'category' => 'upper',
                'side' => 'left',
                'x' => 30,
                'y' => 41,
                'fact' => 'Help us reach high objects, carry toys, and give warm hugs.',
                'audioText' => 'Arms',
            ],
            [
                'key' => 'part_elbow',
                'name' => 'Elbow',
                'marathi' => 'कोपरा (Kopra)',
                'hindi' => 'कोहनी (Kohni)',
                'icon' => '🦾',
                'category' => 'upper',
                'side' => 'right',
                'x' => 26,
                'y' => 47,
                'fact' => 'The flexible hinge joint that lets our arm bend and fold.',
                'audioText' => 'Elbow',
            ],
            [
                'key' => 'part_hands',
                'name' => 'Hands',
                'marathi' => 'हात (Haat / Panja)',
                'hindi' => 'हाथ (Haath)',
                'icon' => '✋',
                'category' => 'sense',
                'side' => 'left',
                'x' => 22,
                'y' => 55,
                'fact' => 'Sense of Touch: We write, paint, clap, and feel warm or soft textures.',
                'audioText' => 'Hands. Used for touching and holding.',
            ],
            [
                'key' => 'part_fingers',
                'name' => 'Fingers',
                'marathi' => 'बोटे (Bote)',
                'hindi' => 'उंगलियाँ (Ungliyan)',
                'icon' => '✌️',
                'category' => 'upper',
                'side' => 'right',
                'x' => 20,
                'y' => 59,
                'fact' => 'Ten nimble fingers that hold crayons, turn book pages, and count.',
                'audioText' => 'Fingers',
            ],
            [
                'key' => 'part_legs',
                'name' => 'Legs',
                'marathi' => 'पाय (Paay)',
                'hindi' => 'टाँगें (Taangein)',
                'icon' => '🦵',
                'category' => 'lower',
                'side' => 'left',
                'x' => 42,
                'y' => 69,
                'fact' => 'Long and powerful limbs that let us walk, leap, run, and skip.',
                'audioText' => 'Legs',
            ],
            [
                'key' => 'part_knees',
                'name' => 'Knees',
                'marathi' => 'गुडघे (Gudghe)',
                'hindi' => 'घुटने (Ghutne)',
                'icon' => '🦿',
                'category' => 'lower',
                'side' => 'right',
                'x' => 43,
                'y' => 77,
                'fact' => 'Bendy joints that allow our legs to sit cross-legged, crouch, and pedal.',
                'audioText' => 'Knees',
            ],
            [
                'key' => 'part_feet',
                'name' => 'Feet',
                'marathi' => 'पावले (Paavle)',
                'hindi' => 'पैर (Pair)',
                'icon' => '🦶',
                'category' => 'lower',
                'side' => 'left',
                'x' => 41,
                'y' => 92,
                'fact' => 'Firm bases that support our body weight and let us stand upright.',
                'audioText' => 'Feet',
            ],
            [
                'key' => 'part_toes',
                'name' => 'Toes',
                'marathi' => 'पायाची बोटे (Paayachi Bote)',
                'hindi' => 'पैर की उंगलियाँ',
                'icon' => '👣',
                'category' => 'lower',
                'side' => 'right',
                'x' => 41,
                'y' => 97,
                'fact' => 'Ten toes at the tips of our feet that give us balance when we sprint.',
                'audioText' => 'Toes',
            ],
        ];

        DB::table('learning_charts')->updateOrInsert(
            ['slug' => self::CHART_SLUG],
            [
                'id' => (string) Str::uuid(),
                'subject' => 'EVS',
                'title' => 'Parts of the Body (शरीराचे अवयव)',
                'description' => 'Interactive reference chart for learning human body parts with visual diagram pointers, spoken pronunciation on hover, and practice tracking.',
                'chart_type' => 'body_parts',
                'chart_data' => json_encode($bodyPartsData, JSON_UNESCAPED_UNICODE),
                'updated_at' => now(),
                'created_at' => now(),
            ]
        );
    }

    public function down(): void
    {
        DB::table('learning_charts')->where('slug', self::CHART_SLUG)->delete();
    }
};
