<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        // 1. Animals Chart Data (24 animals)
        $animalsData = [
            // Wild Animals
            [
                'key' => 'animal_lion',
                'name' => 'Lion',
                'marathi' => 'सिंह (Sinha)',
                'hindi' => 'शेर (Sher)',
                'icon' => '🦁',
                'category' => 'wild',
                'sound' => 'Roar! (डरकाळी)',
                'fact' => 'Known as the King of the Jungle. Male lions have magnificent manes!',
                'audioText' => 'Lion. Lion says Roar. सिंह.',
            ],
            [
                'key' => 'animal_tiger',
                'name' => 'Tiger',
                'marathi' => 'वाघ (Waagh)',
                'hindi' => 'बाघ (Baagh)',
                'icon' => '🐅',
                'category' => 'wild',
                'sound' => 'Growl! (गुरगुर)',
                'fact' => 'The National Animal of India! Every tiger has a unique pattern of stripes.',
                'audioText' => 'Tiger. वाघ. National Animal of India.',
            ],
            [
                'key' => 'animal_elephant',
                'name' => 'Elephant',
                'marathi' => 'हत्ती (Hatti)',
                'hindi' => 'हाथी (Haathi)',
                'icon' => '🐘',
                'category' => 'wild',
                'sound' => 'Trumpet! (चिंकारणे)',
                'fact' => 'The largest land animal on Earth. Uses its long trunk to drink water and pick food.',
                'audioText' => 'Elephant. हत्ती. Elephant has a long trunk.',
            ],
            [
                'key' => 'animal_giraffe',
                'name' => 'Giraffe',
                'marathi' => 'जिराफ (Giraffe)',
                'hindi' => 'जिराफ़ (Giraffe)',
                'icon' => '🦒',
                'category' => 'wild',
                'sound' => 'Hum! (हम्म)',
                'fact' => 'The tallest animal in the world! It has a very long neck to eat leaves from high trees.',
                'audioText' => 'Giraffe. जिराफ. Tallest animal on Earth.',
            ],
            [
                'key' => 'animal_zebra',
                'name' => 'Zebra',
                'marathi' => 'झिब्रा (Zebra)',
                'hindi' => 'ज़ेबरा (Zebra)',
                'icon' => '🦓',
                'category' => 'wild',
                'sound' => 'Bray! (व्हिनव्हिन)',
                'fact' => 'Famous for its black and white stripes which help keep it cool in the sun.',
                'audioText' => 'Zebra. झिब्रा. Black and white stripes.',
            ],
            [
                'key' => 'animal_monkey',
                'name' => 'Monkey',
                'marathi' => 'माकड (Maakad)',
                'hindi' => 'बंदर (Bandar)',
                'icon' => '🐒',
                'category' => 'wild',
                'sound' => 'Chatter! (किलबिल)',
                'fact' => 'Very playful and intelligent! Loves swinging from tree branches using its hands and tail.',
                'audioText' => 'Monkey. माकड. Loves jumping on trees.',
            ],
            [
                'key' => 'animal_bear',
                'name' => 'Bear',
                'marathi' => 'अस्वल (Aswal)',
                'hindi' => 'भालू (Bhalu)',
                'icon' => '🐻',
                'category' => 'wild',
                'sound' => 'Growl! (गुरगुर)',
                'fact' => 'Has thick furry coat and sharp claws. Loves sweet honey, berries, and fish!',
                'audioText' => 'Bear. अस्वल. Loves honey.',
            ],
            [
                'key' => 'animal_kangaroo',
                'name' => 'Kangaroo',
                'marathi' => 'कांगारू (Kangaroo)',
                'hindi' => 'कंगारू (Kangaroo)',
                'icon' => '🦘',
                'category' => 'wild',
                'sound' => 'Chortle! (चुकचुक)',
                'fact' => 'Has strong back legs to hop high! Mother kangaroos carry their babies in a pouch.',
                'audioText' => 'Kangaroo. कांगारू. Hops and carries baby in a pouch.',
            ],
            // Domestic / Farm Animals
            [
                'key' => 'animal_dog',
                'name' => 'Dog',
                'marathi' => 'कुत्रा (Kutra)',
                'hindi' => 'कुत्ता (Kutta)',
                'icon' => '🐕',
                'category' => 'domestic',
                'sound' => 'Woof Woof! (भो-भो)',
                'fact' => 'Human\'s best friend! Very loyal, protects the house, and wags its tail happily.',
                'audioText' => 'Dog. कुत्रा. Dog barks Woof Woof.',
            ],
            [
                'key' => 'animal_cat',
                'name' => 'Cat',
                'marathi' => 'मांजर (Manjar)',
                'hindi' => 'बिल्ली (Billi)',
                'icon' => '🐈',
                'category' => 'domestic',
                'sound' => 'Meow Meow! (म्याऊँ-म्याऊँ)',
                'fact' => 'Very nimble and quiet walker. Can see well in dim light and purrs when happy.',
                'audioText' => 'Cat. मांजर. Cat says Meow Meow.',
            ],
            [
                'key' => 'animal_cow',
                'name' => 'Cow',
                'marathi' => 'गाय (Gaay)',
                'hindi' => 'गाय (Gaay)',
                'icon' => '🐄',
                'category' => 'domestic',
                'sound' => 'Moo Moo! (हंबरणे)',
                'fact' => 'Gives us fresh healthy milk every day which makes our bones and teeth strong.',
                'audioText' => 'Cow. गाय. Cow gives healthy milk.',
            ],
            [
                'key' => 'animal_buffalo',
                'name' => 'Buffalo',
                'marathi' => 'म्हैस (Mhais)',
                'hindi' => 'भैंस (Bhains)',
                'icon' => '🐃',
                'category' => 'domestic',
                'sound' => 'Grunt! (गुर्र)',
                'fact' => 'Very strong and calm farm animal. Loves bathing in cool ponds and rivers.',
                'audioText' => 'Buffalo. म्हैस. Buffalo loves water ponds.',
            ],
            [
                'key' => 'animal_goat',
                'name' => 'Goat',
                'marathi' => 'शेळी (Sheli)',
                'hindi' => 'बकरी (Bakri)',
                'icon' => '🐐',
                'category' => 'domestic',
                'sound' => 'Baa Baa! (बे-बे)',
                'fact' => 'Loves eating fresh grass and leaves. Excellent climber on rocks and hills!',
                'audioText' => 'Goat. शेळी. Goat says Baa Baa.',
            ],
            [
                'key' => 'animal_sheep',
                'name' => 'Sheep',
                'marathi' => 'मेंढी (Mendhi)',
                'hindi' => 'भेड़ (Bhed)',
                'icon' => '🐑',
                'category' => 'domestic',
                'sound' => 'Baa Baa! (म्या-म्या)',
                'fact' => 'Has soft fluffy wool used to knit warm sweaters, caps, and cozy blankets.',
                'audioText' => 'Sheep. मेंढी. Gives warm soft wool.',
            ],
            [
                'key' => 'animal_horse',
                'name' => 'Horse',
                'marathi' => 'घोडा (Ghoda)',
                'hindi' => 'घोड़ा (Ghoda)',
                'icon' => '🐎',
                'category' => 'domestic',
                'sound' => 'Neigh! (खिंकाळणे)',
                'fact' => 'Can run very fast with majestic speed! Can sleep standing up on its four legs.',
                'audioText' => 'Horse. घोडा. Runs very fast.',
            ],
            [
                'key' => 'animal_camel',
                'name' => 'Camel',
                'marathi' => 'उंट (Oont)',
                'hindi' => 'ऊँट (Oont)',
                'icon' => '🐫',
                'category' => 'domestic',
                'sound' => 'Grunt! (घुरघुर)',
                'fact' => 'Known as the Ship of the Desert! Can walk on hot desert sand and store energy in its hump.',
                'audioText' => 'Camel. उंट. Ship of the desert.',
            ],
            [
                'key' => 'animal_rabbit',
                'name' => 'Rabbit',
                'marathi' => 'ससा (Sasa)',
                'hindi' => 'खरगोश (Khargosh)',
                'icon' => '🐇',
                'category' => 'domestic',
                'sound' => 'Squeak! (किचकिच)',
                'fact' => 'Has long ears, fluffy white fur, and loves munching on crunchy sweet carrots!',
                'audioText' => 'Rabbit. ससा. Loves crunchy carrots.',
            ],
            // Water / Sea Animals
            [
                'key' => 'animal_whale',
                'name' => 'Blue Whale',
                'marathi' => 'देवमासा (Devmassa / Whale)',
                'hindi' => 'ब्लू व्हेल (Blue Whale)',
                'icon' => '🐋',
                'category' => 'water',
                'sound' => 'Whale Song! (व्हेलचे गाणे)',
                'fact' => 'The biggest creature ever to live on planet Earth! Breathes air through its blowhole.',
                'audioText' => 'Blue Whale. देवमासा. The biggest creature in the ocean.',
            ],
            [
                'key' => 'animal_dolphin',
                'name' => 'Dolphin',
                'marathi' => 'डॉल्फिन (Dolphin)',
                'hindi' => 'डॉल्फ़िन (Dolphin)',
                'icon' => '🐬',
                'category' => 'water',
                'sound' => 'Click & Whistle! (शिट्टी)',
                'fact' => 'Extremely smart and playful sea animal! Jumps high above the ocean waves.',
                'audioText' => 'Dolphin. डॉल्फिन. Friendly and clever ocean animal.',
            ],
            [
                'key' => 'animal_turtle',
                'name' => 'Sea Turtle',
                'marathi' => 'कासव (Kaasav)',
                'hindi' => 'कछुआ (Kachhua)',
                'icon' => '🐢',
                'category' => 'water',
                'sound' => 'Quiet Splash! (हळूच पोहणे)',
                'fact' => 'Carries a strong protective shell on its back and can swim thousands of ocean miles.',
                'audioText' => 'Turtle. कासव. Has a protective shell and swims calmly.',
            ],
            [
                'key' => 'animal_octopus',
                'name' => 'Octopus',
                'marathi' => 'ऑक्टोपस (Octopus / अष्टपाद)',
                'hindi' => 'ऑक्टोपस (Octopus)',
                'icon' => '🐙',
                'category' => 'water',
                'sound' => 'Suction & Bubble! (बुडबुडे)',
                'fact' => 'Has 8 flexible arms with suction cups, 3 beating hearts, and blue blood!',
                'audioText' => 'Octopus. ऑक्टोपस. Has eight arms and three hearts.',
            ],
            [
                'key' => 'animal_fish',
                'name' => 'Clownfish',
                'marathi' => 'रंगीत मासा (Massa)',
                'hindi' => 'मछली (Machhli)',
                'icon' => '🐠',
                'category' => 'water',
                'sound' => 'Bubble Bubble! (गलगल)',
                'fact' => 'Breathes underwater through gills and swims with smooth fins in colorful coral reefs.',
                'audioText' => 'Fish. मासा. Swims freely in water.',
            ],
            [
                'key' => 'animal_shark',
                'name' => 'Shark',
                'marathi' => 'शार्क मासा (Shark)',
                'hindi' => 'शार्क (Shark)',
                'icon' => '🦈',
                'category' => 'water',
                'sound' => 'Ocean Glide! (जलद पोहणे)',
                'fact' => 'Master swimmer of the deep seas with sharp senses and multiple rows of teeth.',
                'audioText' => 'Shark. शार्क मासा. Swift deep sea swimmer.',
            ],
            [
                'key' => 'animal_crocodile',
                'name' => 'Crocodile',
                'marathi' => 'मगर (Magar)',
                'hindi' => 'मगरमच्छ (Magarmachh)',
                'icon' => '🐊',
                'category' => 'water',
                'sound' => 'Hiss! (फुसकार)',
                'fact' => 'Can swim in rivers and bask under the sun on riverbanks. Very ancient reptile!',
                'audioText' => 'Crocodile. मगर. Swims in river and rests on land.',
            ],
        ];

        // 2. Vegetables Chart Data (20 vegetables)
        $vegetablesData = [
            [
                'key' => 'veg_potato',
                'name' => 'Potato',
                'marathi' => 'बटाटा (Batata)',
                'hindi' => 'आलू (Aloo)',
                'icon' => '🥔',
                'category' => 'root',
                'benefit' => 'Full of healthy carbohydrates that give kids energy to play and study!',
                'clue' => 'Grows under the soil. Used to make delicious Batata Vada, fries, and sabzi.',
                'audioText' => 'Potato. बटाटा. Energy rich root vegetable.',
            ],
            [
                'key' => 'veg_tomato',
                'name' => 'Tomato',
                'marathi' => 'टोमॅटो (Tomato)',
                'hindi' => 'टमाटर (Tamatar)',
                'icon' => '🍅',
                'category' => 'fruit',
                'benefit' => 'Rich in Vitamin C and antioxidants that keep your skin glowing and body healthy.',
                'clue' => 'Bright red, juicy and tangy. Great in fresh salads, soups, and curries.',
                'audioText' => 'Tomato. टोमॅटो. Juicy red vegetable rich in vitamin C.',
            ],
            [
                'key' => 'veg_onion',
                'name' => 'Onion',
                'marathi' => 'कांदा (Kanda)',
                'hindi' => 'प्याज़ (Pyaaz)',
                'icon' => '🧅',
                'category' => 'bulb',
                'benefit' => 'Boosts body immunity and adds wonderful natural aroma to Indian curries.',
                'clue' => 'Has many layers. Peeling it can make your eyes water with natural healthy tears!',
                'audioText' => 'Onion. कांदा. Adds aroma and flavor to food.',
            ],
            [
                'key' => 'veg_carrot',
                'name' => 'Carrot',
                'marathi' => 'गाजर (Gajar)',
                'hindi' => 'गाजर (Gajar)',
                'icon' => '🥕',
                'category' => 'root',
                'benefit' => 'Loaded with Vitamin A (beta-carotene) for super sharp eyesight and vision!',
                'clue' => 'Bright crunchy orange root vegetable. Favorite treat of bunnies and Gajar Ka Halwa!',
                'audioText' => 'Carrot. गाजर. Crunchy root vegetable for sharp eyesight.',
            ],
            [
                'key' => 'veg_spinach',
                'name' => 'Spinach',
                'marathi' => 'पालक (Palak)',
                'hindi' => 'पालक (Palak)',
                'icon' => '🥬',
                'category' => 'leafy',
                'benefit' => 'Packed with iron and calcium to build super strong muscles and blood.',
                'clue' => 'Green leafy vegetable used to make tasty Palak Paneer and hearty soups.',
                'audioText' => 'Spinach. पालक. Iron-rich green leafy vegetable.',
            ],
            [
                'key' => 'veg_peas',
                'name' => 'Green Peas',
                'marathi' => 'मटार (Mataar)',
                'hindi' => 'मटर (Matar)',
                'icon' => '🫛',
                'category' => 'fruit',
                'benefit' => 'Rich in plant protein and dietary fiber for good digestion and growth.',
                'clue' => 'Little sweet green round pearls hiding inside a cozy green pod!',
                'audioText' => 'Green Peas. मटार. Sweet round green pearls.',
            ],
            [
                'key' => 'veg_brinjal',
                'name' => 'Brinjal / Eggplant',
                'marathi' => 'वांगी (Vangi)',
                'hindi' => 'बैंगन (Baingan)',
                'icon' => '🍆',
                'category' => 'fruit',
                'benefit' => 'Known as the King of Vegetables because of its crown! High in fiber.',
                'clue' => 'Glossy purple vegetable with a cute green cap. Famous in Maharashtrian Vangi Bhaat.',
                'audioText' => 'Brinjal. वांगी. Purple vegetable with a green crown.',
            ],
            [
                'key' => 'veg_cauliflower',
                'name' => 'Cauliflower',
                'marathi' => 'फ्लॉवर (Flower / फुलकोबी)',
                'hindi' => 'फूलगोभी (Phoolgobhi)',
                'icon' => '🥦',
                'category' => 'leafy',
                'benefit' => 'Rich in Vitamin C and fiber that helps your tummy feel satisfied and healthy.',
                'clue' => 'Looks like a beautiful white flower bouquet surrounded by green leaves.',
                'audioText' => 'Cauliflower. फ्लॉवर. Looks like a flower bouquet.',
            ],
            [
                'key' => 'veg_cabbage',
                'name' => 'Cabbage',
                'marathi' => 'कोबी (Kobi)',
                'hindi' => 'पत्तागोभी (Pattagobhi)',
                'icon' => '🥗',
                'category' => 'leafy',
                'benefit' => 'Contains lots of healthy water and fiber for active clean digestion.',
                'clue' => 'Round ball of tightly wrapped green leaves. Crunchy in rolls and warm sabzi.',
                'audioText' => 'Cabbage. पत्ता कोबी. Tightly packed green leaves.',
            ],
            [
                'key' => 'veg_ladyfinger',
                'name' => 'Ladyfinger / Okra',
                'marathi' => 'भेंडी (Bhendi)',
                'hindi' => 'भिंडी (Bhindi)',
                'icon' => '🌱',
                'category' => 'fruit',
                'benefit' => 'Great for brain power, memory, and smooth digestive health.',
                'clue' => 'Long slim green pods with tiny white seeds inside that look like little stars!',
                'audioText' => 'Ladyfinger. भेंडी. Slim green pods with star seeds.',
            ],
            [
                'key' => 'veg_capsicum',
                'name' => 'Capsicum / Bell Pepper',
                'marathi' => 'शिमला मिरची (Shimla Mirchi)',
                'hindi' => 'शिमला मिर्च (Shimla Mirch)',
                'icon' => '🫑',
                'category' => 'fruit',
                'benefit' => 'Packed with vitamins that boost immunity against seasonal coughs and colds.',
                'clue' => 'Crunchy and hollow inside with gentle sweet taste. Comes in green, yellow, and red.',
                'audioText' => 'Capsicum. शिमला मिरची. Crunchy bell pepper.',
            ],
            [
                'key' => 'veg_cucumber',
                'name' => 'Cucumber',
                'marathi' => 'काकडी (Kaakdi)',
                'hindi' => 'खीरा (Kheera)',
                'icon' => '🥒',
                'category' => 'fruit',
                'benefit' => 'Contains 95% pure cooling water to keep your body refreshed during hot days.',
                'clue' => 'Cool and crunchy green salad favourite. Delicious with a sprinkle of salt and lemon!',
                'audioText' => 'Cucumber. काकडी. Cool and refreshing hydrating vegetable.',
            ],
            [
                'key' => 'veg_pumpkin',
                'name' => 'Pumpkin',
                'marathi' => 'भोपळा (Bhopla)',
                'hindi' => 'कद्दू (Kaddu)',
                'icon' => '🎃',
                'category' => 'fruit',
                'benefit' => 'Golden flesh packed with Vitamin A, zinc, and wholesome minerals for immunity.',
                'clue' => 'Big golden orange vegetable that grows on ground vines. Used in sweet pumpkin puris!',
                'audioText' => 'Pumpkin. तांबडा भोपळा. Sweet golden vegetable.',
            ],
            [
                'key' => 'veg_beetroot',
                'name' => 'Beetroot',
                'marathi' => 'बीट (Beet)',
                'hindi' => 'चुकंदर (Chukandar)',
                'icon' => '🍠',
                'category' => 'root',
                'benefit' => 'Increases red blood cells and stamina so children can run faster without tiring.',
                'clue' => 'Deep ruby red root vegetable that turns salad and finger tips a lovely pink!',
                'audioText' => 'Beetroot. बीट. Ruby red vegetable for healthy blood.',
            ],
            [
                'key' => 'veg_radish',
                'name' => 'Radish',
                'marathi' => 'मुळा (Mula)',
                'hindi' => 'मूली (Mooli)',
                'icon' => '🪄',
                'category' => 'root',
                'benefit' => 'Purifies the tummy, stimulates appetite, and supports healthy liver function.',
                'clue' => 'Crisp white root with a gentle zesty kick. Eaten fresh in salads and warm parathas.',
                'audioText' => 'Radish. मुळा. Crisp white zesty root vegetable.',
            ],
            [
                'key' => 'veg_corn',
                'name' => 'Sweet Corn',
                'marathi' => 'मका (Maka)',
                'hindi' => 'भुट्टा / मकई (Makka)',
                'icon' => '🌽',
                'category' => 'fruit',
                'benefit' => 'Rich in lutein and dietary fiber that fuels active brains and playful energy.',
                'clue' => 'Golden yellow sweet kernels nestled on a cob. Loved roasted as warm Bhutta!',
                'audioText' => 'Sweet Corn. मका. Juicy golden yellow kernels.',
            ],
            [
                'key' => 'veg_ginger',
                'name' => 'Ginger',
                'marathi' => 'आले (Aale)',
                'hindi' => 'अदरक (Adrak)',
                'icon' => '🫚',
                'category' => 'root',
                'benefit' => 'Natural Ayurvedic medicine that warms the throat and protects from chills.',
                'clue' => 'Knobby aromatic root. Mom adds it to hot masala tea and healing herbal soups.',
                'audioText' => 'Ginger. आले. Healing aromatic root.',
            ],
            [
                'key' => 'veg_garlic',
                'name' => 'Garlic',
                'marathi' => 'लसूण (Lasun)',
                'hindi' => 'लहसुन (Lahsun)',
                'icon' => '🧄',
                'category' => 'bulb',
                'benefit' => 'Powerful natural antibacterial superfood that keeps the heart and body healthy.',
                'clue' => 'Made of little white cloves wrapped in paper-thin skin with a punchy aroma.',
                'audioText' => 'Garlic. लसूण. Healthy aroma cloves.',
            ],
            [
                'key' => 'veg_bitter_gourd',
                'name' => 'Bitter Gourd',
                'marathi' => 'कारले (Karle)',
                'hindi' => 'करेला (Karela)',
                'icon' => '🥒',
                'category' => 'fruit',
                'benefit' => 'Super cleanser of blood that strengthens gut immunity and regulates glucose.',
                'clue' => 'Bumpy green vegetable with a bitter taste that makes you super strong inside!',
                'audioText' => 'Bitter Gourd. कारले. Bitter taste but super healthy cleanser.',
            ],
            [
                'key' => 'veg_bottle_gourd',
                'name' => 'Bottle Gourd',
                'marathi' => 'दुधी भोपळा (Dudhi Bhopla)',
                'hindi' => 'लौकी (Lauki)',
                'icon' => '🍈',
                'category' => 'fruit',
                'benefit' => 'Gentle on little stomachs, naturally cool and hydrating for deep calmness.',
                'clue' => 'Smooth pale green gourd used to make wholesome Dudhi Halwa and soft koftas.',
                'audioText' => 'Bottle Gourd. दुधी भोपळा. Gentle cooling vegetable.',
            ],
        ];

        // 3. Birds Chart Data (16 birds)
        $birdsData = [
            [
                'key' => 'bird_peacock',
                'name' => 'Peacock',
                'marathi' => 'मोर (Mor)',
                'hindi' => 'मोर (Mor)',
                'icon' => '🦚',
                'category' => 'garden',
                'sound' => 'May-awe! (पिहू-पिहू)',
                'fact' => 'National Bird of India! Spreads its iridescent royal blue and green feathers in the monsoon rain.',
                'audioText' => 'Peacock. मोर. National Bird of India with gorgeous feathers.',
            ],
            [
                'key' => 'bird_parrot',
                'name' => 'Parrot',
                'marathi' => 'पोपट (Popat)',
                'hindi' => 'तोता (Tota)',
                'icon' => '🦜',
                'category' => 'garden',
                'sound' => 'Squawk! (मिठू-मिठू)',
                'fact' => 'Bright green feathers with a curved red beak. Can cleverly mimic human words and loves green chilies!',
                'audioText' => 'Parrot. पोपट. Green bird with a red beak that mimics speech.',
            ],
            [
                'key' => 'bird_sparrow',
                'name' => 'Sparrow',
                'marathi' => 'चिमणी (Chimni)',
                'hindi' => 'गौरैया (Gauraiya)',
                'icon' => '🐤',
                'category' => 'garden',
                'sound' => 'Cheep Cheep! (चिव-चिव)',
                'fact' => 'Small friendly brown bird that visits home balconies and hops looking for grain seeds.',
                'audioText' => 'Sparrow. चिमणी. Little cheerful garden bird that chirps.',
            ],
            [
                'key' => 'bird_pigeon',
                'name' => 'Pigeon / Dove',
                'marathi' => 'कबूतर (Kabootar)',
                'hindi' => 'कबूतर (Kabootar)',
                'icon' => '🕊️',
                'category' => 'garden',
                'sound' => 'Coo Coo! (गुटरगूँ-गुटरगूँ)',
                'fact' => 'Symbol of peace. Has incredible navigation memory and can find its way home from miles away.',
                'audioText' => 'Pigeon. कबूतर. Gentle bird symbol of peace.',
            ],
            [
                'key' => 'bird_crow',
                'name' => 'Crow',
                'marathi' => 'कावळा (Kaawla)',
                'hindi' => 'कौआ (Kauva)',
                'icon' => '🐦‍⬛',
                'category' => 'garden',
                'sound' => 'Caw Caw! (काव-काव)',
                'fact' => 'One of the smartest birds in the world! Can solve puzzles, recognize human faces, and use tools.',
                'audioText' => 'Crow. कावळा. Super smart black bird.',
            ],
            [
                'key' => 'bird_eagle',
                'name' => 'Eagle',
                'marathi' => 'गरुड (Garud)',
                'hindi' => 'चील / गरुड़ (Garud)',
                'icon' => '🦅',
                'category' => 'wild',
                'sound' => 'Screech! (किंचाळणे)',
                'fact' => 'Soars high in the sky with powerful wings and razor-sharp vision that spots food from a kilometer away.',
                'audioText' => 'Eagle. गरुड. Powerful flyer with sharp vision.',
            ],
            [
                'key' => 'bird_owl',
                'name' => 'Owl',
                'marathi' => 'घुबड (Ghubad)',
                'hindi' => 'उल्लू (Ullu)',
                'icon' => '🦉',
                'category' => 'wild',
                'sound' => 'Hoot Hoot! (हूट-हूट)',
                'fact' => 'Nocturnal bird of wisdom! Can rotate its head almost all the way around and flies completely silently.',
                'audioText' => 'Owl. घुबड. Nocturnal bird that sees in the dark.',
            ],
            [
                'key' => 'bird_duck',
                'name' => 'Duck',
                'marathi' => 'बदक (Badak)',
                'hindi' => 'बत्तख (Battakh)',
                'icon' => '🦆',
                'category' => 'water',
                'sound' => 'Quack Quack! (क्वॅक-क्वॅक)',
                'fact' => 'Has webbed feet like natural swimming paddles and waterproof feathers that stay dry in ponds.',
                'audioText' => 'Duck. बदक. Duck says Quack Quack.',
            ],
            [
                'key' => 'bird_swan',
                'name' => 'Swan',
                'marathi' => 'हंस (Hansa)',
                'hindi' => 'हंस (Hans)',
                'icon' => '🦢',
                'category' => 'water',
                'sound' => 'Honk! (मधुर आवाज)',
                'fact' => 'Graceful white bird with a long elegant neck that glides peacefully on serene lakes.',
                'audioText' => 'Swan. हंस. Graceful white water bird.',
            ],
            [
                'key' => 'bird_flamingo',
                'name' => 'Flamingo',
                'marathi' => 'रोहित पक्षी / अग्निपंख (Flamingo)',
                'hindi' => 'राजहंस (Flamingo)',
                'icon' => '🦩',
                'category' => 'water',
                'sound' => 'Nasal Honk! (ध्वनी)',
                'fact' => 'Famous for its bright pink feathers and standing comfortably on one skinny leg in mudflats.',
                'audioText' => 'Flamingo. रोहित पक्षी. Beautiful pink bird that stands on one leg.',
            ],
            [
                'key' => 'bird_kingfisher',
                'name' => 'Kingfisher',
                'marathi' => 'खंड्या (Khandya)',
                'hindi' => 'रामचिरैया / नीलकंठ (Kingfisher)',
                'icon' => '🐦',
                'category' => 'water',
                'sound' => 'High Whistle! (तीव्र शिट्टी)',
                'fact' => 'Has dazzling turquoise blue feathers and dives like a lightning arrow into clear streams to catch tiny fish.',
                'audioText' => 'Kingfisher. खंड्या. Dazzling turquoise bird that dives for fish.',
            ],
            [
                'key' => 'bird_woodpecker',
                'name' => 'Woodpecker',
                'marathi' => 'सुतार पक्षी (Sutaar Pakshi)',
                'hindi' => 'कठफोड़वा (Kathphodwa)',
                'icon' => '🪶',
                'category' => 'wild',
                'sound' => 'Tap-Tap-Tap! (टक-टक)',
                'fact' => 'Pecks tree bark with its chisel-like beak at incredible speed to find hidden insects.',
                'audioText' => 'Woodpecker. सुतार पक्षी. Pecks tree bark to find insects.',
            ],
            [
                'key' => 'bird_hen',
                'name' => 'Rooster & Hen',
                'marathi' => 'कोंबडा / कोंबडी (Kombda)',
                'hindi' => 'मुर्गा / मुर्गी (Murga)',
                'icon' => '🐓',
                'category' => 'garden',
                'sound' => 'Cock-a-doodle-doo! (कुकुच-कू)',
                'fact' => 'Wakes up the whole farm at dawn with a cheerful morning crow! Has a red crest on its head.',
                'audioText' => 'Rooster. कोंबडा. Rooster crows at dawn.',
            ],
            [
                'key' => 'bird_ostrich',
                'name' => 'Ostrich',
                'marathi' => 'शहामृग (Shahamrug)',
                'hindi' => 'शुतुरमुर्ग (Shuturmurg)',
                'icon' => '🦤',
                'category' => 'flightless',
                'sound' => 'Boom & Hiss! (गुंजण)',
                'fact' => 'The largest and heaviest bird on Earth! Cannot fly, but can sprint as fast as a racing car.',
                'audioText' => 'Ostrich. शहामृग. The largest bird in the world.',
            ],
            [
                'key' => 'bird_penguin',
                'name' => 'Penguin',
                'marathi' => 'पेंग्विन (Penguin)',
                'hindi' => 'पेंगुइन (Penguin)',
                'icon' => '🐧',
                'category' => 'flightless',
                'sound' => 'Honk Bray! (ध्वनी)',
                'fact' => 'Waddles adorably on snowy Antarctic ice and slides on its tummy like a joyful sled!',
                'audioText' => 'Penguin. पेंग्विन. Waddles on snow and swims in chilly seas.',
            ],
            [
                'key' => 'bird_cuckoo',
                'name' => 'Cuckoo / Koel',
                'marathi' => 'कोकिळा (Kokila)',
                'hindi' => 'कोयल (Koel)',
                'icon' => '🐤',
                'category' => 'garden',
                'sound' => 'Koo-oo! Koo-oo! (कुहू-कुहू)',
                'fact' => 'Famous for its melodious sweet singing in the spring among fragrant mango blossoms.',
                'audioText' => 'Cuckoo. कोकिळा. Sings sweet melody in spring.',
            ],
        ];

        // 4. Emotions Chart Data (16 emotions)
        $emotionsData = [
            [
                'key' => 'emotion_happy',
                'name' => 'Happy',
                'marathi' => 'आनंदी (Aanandi)',
                'hindi' => 'खुश (Khush)',
                'icon' => '😊',
                'category' => 'positive',
                'color' => '#f59e0b',
                'cue' => 'Big glowing smile, sparkling eyes, bouncing posture!',
                'tool' => 'Share your joyful smile with a friend or family member!',
                'audioText' => 'Happy. आनंदी. Feeling cheerful and full of bright joy.',
            ],
            [
                'key' => 'emotion_excited',
                'name' => 'Excited',
                'marathi' => 'उत्साही (Utsahi)',
                'hindi' => 'उत्साहित (Utsahit)',
                'icon' => '🤩',
                'category' => 'positive',
                'color' => '#ea580c',
                'cue' => 'Heart fluttering with happiness, lots of energy to jump and cheer!',
                'tool' => 'Channel that fun energy into drawing, dancing, or sharing a good story!',
                'audioText' => 'Excited. उत्साही. Bursting with fun energy and anticipation.',
            ],
            [
                'key' => 'emotion_proud',
                'name' => 'Proud',
                'marathi' => 'अभिमान (Abhimaan)',
                'hindi' => 'गर्व (Garv)',
                'icon' => '🥳',
                'category' => 'positive',
                'color' => '#8b5cf6',
                'cue' => 'Standing tall, warm heart, knowing you tried hard and succeeded!',
                'tool' => 'Give yourself a high five or pat on the back! You earned it!',
                'audioText' => 'Proud. मला अभिमान वाटतो. Celebrate your effort and achievement.',
            ],
            [
                'key' => 'emotion_loved',
                'name' => 'Loved & Cared For',
                'marathi' => 'मायेची भावना (Maaya / Prem)',
                'hindi' => 'प्यार (Pyaar)',
                'icon' => '🥰',
                'category' => 'positive',
                'color' => '#ec4899',
                'cue' => 'Warm cozy feeling inside your chest, feeling safe and cherished.',
                'tool' => 'Give your parent, teacher, or pet a gentle warm hug.',
                'audioText' => 'Loved. प्रेम आणि माया. Feeling safe, cherished, and warm.',
            ],
            [
                'key' => 'emotion_calm',
                'name' => 'Calm & Peaceful',
                'marathi' => 'शांत (Shaant)',
                'hindi' => 'शांत (Shaant)',
                'icon' => '😌',
                'category' => 'calm',
                'color' => '#10b981',
                'cue' => 'Slow steady breathing, relaxed shoulders, peaceful mind.',
                'tool' => 'Close your eyes, feel the gentle breeze, and enjoy the quiet moment.',
                'audioText' => 'Calm. शांत. Relaxed and peaceful like a quiet lake.',
            ],
            [
                'key' => 'emotion_curious',
                'name' => 'Curious',
                'marathi' => 'उत्सुक (Utsuk)',
                'hindi' => 'जिज्ञासु (Jigyasu)',
                'icon' => '🧐',
                'category' => 'calm',
                'color' => '#0284c7',
                'cue' => 'Tilted head, questioning look, eager to explore and learn new things!',
                'tool' => 'Ask a thoughtful question like "Why?" or "How does that work?"',
                'audioText' => 'Curious. उत्सुक. Ready to ask questions and discover the world.',
            ],
            [
                'key' => 'emotion_grateful',
                'name' => 'Grateful & Thankful',
                'marathi' => 'कृतज्ञ (Krutadnya)',
                'hindi' => 'आभारी (Aabhari)',
                'icon' => '🙏',
                'category' => 'positive',
                'color' => '#14b8a6',
                'cue' => 'Appreciating the good people and blessings around you.',
                'tool' => 'Say a sincere "Thank You" to someone who helped you today.',
                'audioText' => 'Grateful. कृतज्ञ. Saying thank you for the good things in life.',
            ],
            [
                'key' => 'emotion_brave',
                'name' => 'Brave & Courageous',
                'marathi' => 'शूर / धाडसी (Dhaadsi)',
                'hindi' => 'बहादुर (Bahadur)',
                'icon' => '🦁',
                'category' => 'positive',
                'color' => '#d97706',
                'cue' => 'Feeling a little nervous, but choosing to try anyway!',
                'tool' => 'Say to yourself: "I am strong, I can try my best!"',
                'audioText' => 'Brave. धाडसी. Taking courage to try even when things are new.',
            ],
            [
                'key' => 'emotion_sad',
                'name' => 'Sad',
                'marathi' => 'दुःखी (Dukkhi)',
                'hindi' => 'उदास (Udas)',
                'icon' => '😢',
                'category' => 'big_feelings',
                'color' => '#3b82f6',
                'cue' => 'Drooping mouth, heavy feeling in chest, teary eyes.',
                'tool' => 'It is okay to cry. Talk to someone who cares, or snuggle with a cozy pillow.',
                'audioText' => 'Sad. दुःखी. Sadness is normal. Talk to someone who loves you.',
            ],
            [
                'key' => 'emotion_angry',
                'name' => 'Angry / Mad',
                'marathi' => 'रागावलेला (Raagaavlela)',
                'hindi' => 'गुस्सा (Gussa)',
                'icon' => '😠',
                'category' => 'big_feelings',
                'color' => '#ef4444',
                'cue' => 'Clenched fists, warm cheeks, tense jaw, fast heartbeat.',
                'tool' => 'Take 3 deep dinosaur breaths: breathe in slow through nose, blow out slow like cooling soup.',
                'audioText' => 'Angry. राग आला आहे. Stop and take three deep breaths to cool down.',
            ],
            [
                'key' => 'emotion_scared',
                'name' => 'Scared / Afraid',
                'marathi' => 'घाबरलेला (Ghaabarlela)',
                'hindi' => 'डरा हुआ (Dara hua)',
                'icon' => '😨',
                'category' => 'big_feelings',
                'color' => '#7c3aed',
                'cue' => 'Fast heartbeat, wide eyes, wanting to hide or find comfort.',
                'tool' => 'Hold a grown-up\'s hand, look around for 3 things you can see and touch.',
                'audioText' => 'Scared. भीती वाटत आहे. You are safe. Hold a hand and take slow breaths.',
            ],
            [
                'key' => 'emotion_surprised',
                'name' => 'Surprised',
                'marathi' => 'चकित (Chakit)',
                'hindi' => 'हैरान (Hairan)',
                'icon' => '😲',
                'category' => 'calm',
                'color' => '#06b6d4',
                'cue' => 'Raised eyebrows, wide open mouth, gasp of astonishment!',
                'tool' => 'Take a second to process what just happened: "Wow! Look at that!"',
                'audioText' => 'Surprised. चकित. Something unexpected and wondrous happened!',
            ],
            [
                'key' => 'emotion_confused',
                'name' => 'Confused',
                'marathi' => 'गोंधळलेला (Gondhal-lela)',
                'hindi' => 'उलझन में (Uljhan)',
                'icon' => '🤔',
                'category' => 'calm',
                'color' => '#64748b',
                'cue' => 'Scratched head, wrinkled brow, wondering what something means.',
                'tool' => 'Raise your hand and ask: "Could you please explain that again?"',
                'audioText' => 'Confused. गोंधळ झाला आहे. It is great to ask questions to understand.',
            ],
            [
                'key' => 'emotion_tired',
                'name' => 'Tired / Sleepy',
                'marathi' => 'दमलेला / थकलेला (Thaklela)',
                'hindi' => 'थका हुआ (Thaka hua)',
                'icon' => '🥱',
                'category' => 'calm',
                'color' => '#6b7280',
                'cue' => 'Heavy eyelids, yawning, low energy after a busy active day.',
                'tool' => 'Drink some fresh water, rest your head, and enjoy a cozy nap or early bedtime.',
                'audioText' => 'Tired. थकवा जाणवतो आहे. Time to rest and recharge your battery.',
            ],
            [
                'key' => 'emotion_shy',
                'name' => 'Shy',
                'marathi' => 'लाजाळू (Laajaalu)',
                'hindi' => 'शर्मीला (Sharmila)',
                'icon' => '🥺',
                'category' => 'calm',
                'color' => '#a855f7',
                'cue' => 'Hiding face slightly, soft voice, hesitant to step in front of crowd.',
                'tool' => 'Take your time. A gentle wave or warm smile is a wonderful way to connect.',
                'audioText' => 'Shy. लाजाळू. It is okay to take your time to warm up.',
            ],
            [
                'key' => 'emotion_frustrated',
                'name' => 'Frustrated',
                'marathi' => 'वैतागलेला (Vaitaglela)',
                'hindi' => 'निराश (Niraash)',
                'icon' => '😤',
                'category' => 'big_feelings',
                'color' => '#f97316',
                'cue' => 'Trying hard at a tough puzzle or challenge when things don\'t work immediately.',
                'tool' => 'Take a 1-minute brain break. Remember: "Mistakes help our brain grow!"',
                'audioText' => 'Frustrated. वैताग आला आहे. Take a short pause. You will get it with practice!',
            ],
        ];

        // Insert or update all 4 charts into learning_charts table
        DB::table('learning_charts')->updateOrInsert(
            ['slug' => 'animals'],
            [
                'id' => (string) Str::uuid(),
                'subject' => 'EVS',
                'title' => 'Animals & Sounds (प्राणी आणि आवाज)',
                'description' => 'Interactive reference chart for wild, farm, and ocean animals with authentic sounds, bilingual names, and quiz.',
                'chart_type' => 'animals',
                'chart_data' => json_encode($animalsData, JSON_UNESCAPED_UNICODE),
                'updated_at' => $now,
                'created_at' => $now,
            ]
        );

        DB::table('learning_charts')->updateOrInsert(
            ['slug' => 'vegetables'],
            [
                'id' => (string) Str::uuid(),
                'subject' => 'EVS',
                'title' => 'Healthy Vegetables (पौष्टिक भाज्या)',
                'description' => 'Interactive reference chart of everyday vegetables with nutritional benefits, Marathi names, and identification quiz.',
                'chart_type' => 'vegetables',
                'chart_data' => json_encode($vegetablesData, JSON_UNESCAPED_UNICODE),
                'updated_at' => $now,
                'created_at' => $now,
            ]
        );

        DB::table('learning_charts')->updateOrInsert(
            ['slug' => 'birds'],
            [
                'id' => (string) Str::uuid(),
                'subject' => 'EVS',
                'title' => 'Beautiful Birds (सुंदर पक्षी)',
                'description' => 'Interactive reference chart of Indian and world birds with bird calls, fascinating facts, and quiz challenge.',
                'chart_type' => 'birds',
                'chart_data' => json_encode($birdsData, JSON_UNESCAPED_UNICODE),
                'updated_at' => $now,
                'created_at' => $now,
            ]
        );

        DB::table('learning_charts')->updateOrInsert(
            ['slug' => 'emotions'],
            [
                'id' => (string) Str::uuid(),
                'subject' => 'Life Skills',
                'title' => 'Feelings & Emotions (भावना आणि मनःस्थिती)',
                'description' => 'Interactive social-emotional chart helping children identify feelings, body cues, and positive calming coping tools.',
                'chart_type' => 'emotions',
                'chart_data' => json_encode($emotionsData, JSON_UNESCAPED_UNICODE),
                'updated_at' => $now,
                'created_at' => $now,
            ]
        );
    }

    public function down(): void
    {
        DB::table('learning_charts')->whereIn('slug', ['animals', 'vegetables', 'birds', 'emotions'])->delete();
    }
};
