import { VisualChartItem } from "./VisualLearningChartGrid";

export const DEFAULT_ANIMALS: VisualChartItem[] = [
  {
    key: "animal_lion",
    name: "Lion",
    marathi: "सिंह (Sinha)",
    hindi: "शेर (Sher)",
    icon: "🦁",
    image: "/assets/charts/animal_lion.png",
    category: "wild",
    sound: "Roar! (डरकाळी)",
    fact: "King of the Jungle! Male lions have magnificent fluffy manes.",
    audioText: "Lion. Lion says Roar. सिंह.",
  },
  {
    key: "animal_tiger",
    name: "Tiger",
    marathi: "वाघ (Waagh)",
    hindi: "बाघ (Baagh)",
    icon: "🐅",
    image: "/assets/charts/animal_tiger.png",
    category: "wild",
    sound: "Growl! (गुरगुर)",
    fact: "National Animal of India! Every tiger has a unique pattern of stripes.",
    audioText: "Tiger. वाघ. National Animal of India.",
  },
  {
    key: "animal_elephant",
    name: "Elephant",
    marathi: "हत्ती (Hatti)",
    hindi: "हाथी (Haathi)",
    icon: "🐘",
    image: "/assets/charts/animal_elephant.png",
    category: "wild",
    sound: "Trumpet! (चिंकारणे)",
    fact: "Largest land animal on Earth with big ears and a long versatile trunk.",
    audioText: "Elephant. हत्ती. Elephant has a long trunk.",
  },
  {
    key: "animal_giraffe",
    name: "Giraffe",
    marathi: "जिराफ (Giraffe)",
    hindi: "जिराफ़ (Giraffe)",
    icon: "🦒",
    image: "/assets/charts/animal_giraffe.png",
    category: "wild",
    sound: "Hum! (हम्म)",
    fact: "Tallest animal on Earth! Reaches sweet leaves at the tops of trees.",
    audioText: "Giraffe. जिराफ. Tallest animal on Earth.",
  },
  {
    key: "animal_zebra",
    name: "Zebra",
    marathi: "झिब्रा (Zebra)",
    hindi: "ज़ेबरा (Zebra)",
    icon: "🦓",
    image: "/assets/charts/animal_zebra.png",
    category: "wild",
    sound: "Bray! (व्हिनव्हिन)",
    fact: "Famous for black and white stripes that act as a natural sunscreen.",
    audioText: "Zebra. झिब्रा. Black and white stripes.",
  },
  {
    key: "animal_monkey",
    name: "Monkey",
    marathi: "माकड (Maakad)",
    hindi: "बंदर (Bandar)",
    icon: "🐒",
    image: "/assets/charts/animal_monkey.png",
    category: "wild",
    sound: "Chatter! (किलबिल)",
    fact: "Playful acrobats who love swinging on branches and munching fruits.",
    audioText: "Monkey. माकड. Loves jumping on trees.",
  },
  {
    key: "animal_bear",
    name: "Bear",
    marathi: "अस्वल (Aswal)",
    hindi: "भालू (Bhalu)",
    icon: "🐻",
    image: "/assets/charts/animal_bear.png",
    category: "wild",
    sound: "Growl! (गुरगुर)",
    fact: "Has thick warm fur, strong paws, and loves honey and fresh berries.",
    audioText: "Bear. अस्वल. Loves honey.",
  },
  {
    key: "animal_kangaroo",
    name: "Kangaroo",
    marathi: "कांगारू (Kangaroo)",
    hindi: "कंगारू (Kangaroo)",
    icon: "🦘",
    image: "/assets/charts/animal_kangaroo.png",
    category: "wild",
    sound: "Chortle! (चुकचुक)",
    fact: "Champion jumpers who keep their tiny joeys in a cozy front pouch.",
    audioText: "Kangaroo. कांगारू. Hops and carries baby in a pouch.",
  },
  {
    key: "animal_dog",
    name: "Dog",
    marathi: "कुत्रा (Kutra)",
    hindi: "कुत्ता (Kutta)",
    icon: "🐕",
    image: "/assets/charts/animal_dog.png",
    category: "domestic",
    sound: "Woof Woof! (भो-भो)",
    fact: "Faithful and loyal companion! Wags its tail and loves fetch games.",
    audioText: "Dog. कुत्रा. Dog barks Woof Woof.",
  },
  {
    key: "animal_cat",
    name: "Cat",
    marathi: "मांजर (Manjar)",
    hindi: "बिल्ली (Billi)",
    icon: "🐈",
    image: "/assets/charts/animal_cat.png",
    category: "domestic",
    sound: "Meow Meow! (म्याऊँ-म्याऊँ)",
    fact: "Agile, quiet, and sees well in dim light. Purrs softly when happy.",
    audioText: "Cat. मांजर. Cat says Meow Meow.",
  },
  {
    key: "animal_cow",
    name: "Cow",
    marathi: "गाय (Gaay)",
    hindi: "गाय (Gaay)",
    icon: "🐄",
    image: "/assets/charts/animal_cow.png",
    category: "domestic",
    sound: "Moo Moo! (हंबरणे)",
    fact: "Gentle mother of the farm! Gives us calcium-rich fresh milk.",
    audioText: "Cow. गाय. Cow gives healthy milk.",
  },
  {
    key: "animal_buffalo",
    name: "Buffalo",
    marathi: "म्हैस (Mhais)",
    hindi: "भैंस (Bhains)",
    icon: "🐃",
    image: "/assets/charts/animal_buffalo.png",
    category: "domestic",
    sound: "Grunt! (गुर्र)",
    fact: "Strong farm helper who loves cooling off in muddy river ponds.",
    audioText: "Buffalo. म्हैस. Buffalo loves water ponds.",
  },
  {
    key: "animal_goat",
    name: "Goat",
    marathi: "शेळी (Sheli)",
    hindi: "बकरी (Bakri)",
    icon: "🐐",
    image: "/assets/charts/animal_goat.png",
    category: "domestic",
    sound: "Baa Baa! (बे-बे)",
    fact: "Sure-footed climber that loves fresh green grass and tender leaves.",
    audioText: "Goat. शेळी. Goat says Baa Baa.",
  },
  {
    key: "animal_sheep",
    name: "Sheep",
    marathi: "मेंढी (Mendhi)",
    hindi: "भेड़ (Bhed)",
    icon: "🐑",
    image: "/assets/charts/animal_sheep.png",
    category: "domestic",
    sound: "Baa Baa! (म्या-म्या)",
    fact: "Produces soft fluffy natural wool for warm winter sweaters.",
    audioText: "Sheep. मेंढी. Gives warm soft wool.",
  },
  {
    key: "animal_horse",
    name: "Horse",
    marathi: "घोडा (Ghoda)",
    hindi: "घोड़ा (Ghoda)",
    icon: "🐎",
    image: "/assets/charts/animal_horse.png",
    category: "domestic",
    sound: "Neigh! (खिंकाळणे)",
    fact: "Magnificent runner with incredible stamina. Can sleep standing up.",
    audioText: "Horse. घोडा. Runs very fast.",
  },
  {
    key: "animal_camel",
    name: "Camel",
    marathi: "उंट (Oont)",
    hindi: "ऊँट (Oont)",
    icon: "🐫",
    image: "/assets/charts/animal_camel.png",
    category: "domestic",
    sound: "Grunt! (घुरघुर)",
    fact: "Ship of the Desert! Wide padded feet walk smoothly across sandy dunes.",
    audioText: "Camel. उंट. Ship of the desert.",
  },
  {
    key: "animal_rabbit",
    name: "Rabbit",
    marathi: "ससा (Sasa)",
    hindi: "खरगोश (Khargosh)",
    icon: "🐇",
    image: "/assets/charts/animal_rabbit.png",
    category: "domestic",
    sound: "Squeak! (किचकिच)",
    fact: "Cute twitching nose, soft long ears, and a huge love for crunchy carrots.",
    audioText: "Rabbit. ससा. Loves crunchy carrots.",
  },
  {
    key: "animal_whale",
    name: "Blue Whale",
    marathi: "देवमासा (Devmassa)",
    hindi: "ब्लू व्हेल (Whale)",
    icon: "🐋",
    image: "/assets/charts/animal_whale.png",
    category: "water",
    sound: "Whale Song! (व्हेलचे गाणे)",
    fact: "Largest animal on the entire planet Earth! Sings deep ocean melodies.",
    audioText: "Blue Whale. देवमासा. The biggest creature in the ocean.",
  },
  {
    key: "animal_dolphin",
    name: "Dolphin",
    marathi: "डॉल्फिन (Dolphin)",
    hindi: "डॉल्फ़िन (Dolphin)",
    icon: "🐬",
    image: "/assets/charts/animal_dolphin.png",
    category: "water",
    sound: "Click & Whistle! (शिट्टी)",
    fact: "Playful, friendly, and super intelligent ocean acrobat.",
    audioText: "Dolphin. डॉल्फिन. Friendly and clever ocean animal.",
  },
  {
    key: "animal_turtle",
    name: "Sea Turtle",
    marathi: "कासव (Kaasav)",
    hindi: "कछुआ (Kachhua)",
    icon: "🐢",
    image: "/assets/charts/animal_turtle.png",
    category: "water",
    sound: "Quiet Splash! (हळूच पोहणे)",
    fact: "Ancient ocean traveler that glides through coral reefs with flipper paddles.",
    audioText: "Turtle. कासव. Has a protective shell and swims calmly.",
  },
  {
    key: "animal_octopus",
    name: "Octopus",
    marathi: "ऑक्टोपस (Octopus)",
    hindi: "ऑक्टोपस (Octopus)",
    icon: "🐙",
    image: "/assets/charts/animal_octopus.png",
    category: "water",
    sound: "Bubble Bubble! (बुडबुडे)",
    fact: "Has 8 flexible arms with suction grips, 3 hearts, and blue blood.",
    audioText: "Octopus. ऑक्टोपस. Has eight arms and three hearts.",
  },
  {
    key: "animal_fish",
    name: "Clownfish",
    marathi: "मासा (Massa)",
    hindi: "मछली (Machhli)",
    icon: "🐠",
    image: "/assets/charts/animal_fish.png",
    category: "water",
    sound: "Bubble! (गलगल)",
    fact: "Breathes underwater through gills and lives safely in sea anemones.",
    audioText: "Fish. मासा. Swims freely in water.",
  },
  {
    key: "animal_shark",
    name: "Shark",
    marathi: "शार्क (Shark)",
    hindi: "शार्क (Shark)",
    icon: "🦈",
    image: "/assets/charts/animal_shark.png",
    category: "water",
    sound: "Glide! (जलद पोहणे)",
    fact: "Swift deep-sea swimmer with keen senses and streamlined cartilage skeleton.",
    audioText: "Shark. शार्क मासा. Swift deep sea swimmer.",
  },
  {
    key: "animal_crocodile",
    name: "Crocodile",
    marathi: "मगर (Magar)",
    hindi: "मगरमच्छ (Magarmachh)",
    icon: "🐊",
    image: "/assets/charts/animal_crocodile.png",
    category: "water",
    sound: "Hiss! (फुसकार)",
    fact: "Ancient reptile that swims in rivers and basks warm in the sunshine.",
    audioText: "Crocodile. मगर. Swims in river and rests on land.",
  },
];

export const DEFAULT_VEGETABLES: VisualChartItem[] = [
  {
    key: "veg_potato",
    name: "Potato",
    marathi: "बटाटा (Batata)",
    hindi: "आलू (Aloo)",
    icon: "🥔",
    image: "/assets/charts/veg_potato.png",
    category: "root",
    benefit: "High energy carbs that power outdoor running and studying!",
    clue: "Grows under ground soil. Makes Batata Vada, fries, and aloo parathas.",
    audioText: "Potato. बटाटा. Energy rich root vegetable.",
  },
  {
    key: "veg_tomato",
    name: "Tomato",
    marathi: "टोमॅटो (Tomato)",
    hindi: "टमाटर (Tamatar)",
    icon: "🍅",
    image: "/assets/charts/veg_tomato.png",
    category: "fruit",
    benefit: "Vitamin C and antioxidants for glowing skin and immunity.",
    clue: "Juicy, bright red, and tangy in fresh salads, soups, and curries.",
    audioText: "Tomato. टोमॅटो. Juicy red vegetable rich in vitamin C.",
  },
  {
    key: "veg_onion",
    name: "Onion",
    marathi: "कांदा (Kanda)",
    hindi: "प्याज़ (Pyaaz)",
    icon: "🧅",
    image: "/assets/charts/veg_onion.png",
    category: "bulb",
    benefit: "Natural body defense booster and heart health protector.",
    clue: "Many purple-pink layers that add wonderful flavor to Indian cooking.",
    audioText: "Onion. कांदा. Adds aroma and flavor to food.",
  },
  {
    key: "veg_carrot",
    name: "Carrot",
    marathi: "गाजर (Gajar)",
    hindi: "गाजर (Gajar)",
    icon: "🥕",
    image: "/assets/charts/veg_carrot.png",
    category: "root",
    benefit: "Loaded with Vitamin A beta-carotene for eagle-sharp eyesight!",
    clue: "Bright crunchy orange root vegetable. Favorite of rabbits and halwa!",
    audioText: "Carrot. गाजर. Crunchy root vegetable for sharp eyesight.",
  },
  {
    key: "veg_spinach",
    name: "Spinach",
    marathi: "पालक (Palak)",
    hindi: "पालक (Palak)",
    icon: "🥬",
    image: "/assets/charts/veg_spinach.png",
    category: "leafy",
    benefit: "Rich in iron and calcium for super strong bones and muscles.",
    clue: "Emerald green leafy vegetable famous in Palak Paneer.",
    audioText: "Spinach. पालक. Iron-rich green leafy vegetable.",
  },
  {
    key: "veg_peas",
    name: "Green Peas",
    marathi: "मटार (Mataar)",
    hindi: "मटर (Matar)",
    icon: "🫛",
    image: "/assets/charts/veg_peas.png",
    category: "fruit",
    benefit: "Plant protein and fiber for smooth tummy digestion and growth.",
    clue: "Sweet green pearls hiding in a snug pod. Delicious in Matar Pulao!",
    audioText: "Green Peas. मटार. Sweet round green pearls.",
  },
  {
    key: "veg_brinjal",
    name: "Brinjal / Eggplant",
    marathi: "वांगी (Vangi)",
    hindi: "बैंगन (Baingan)",
    icon: "🍆",
    image: "/assets/charts/veg_brinjal.png",
    category: "fruit",
    benefit: "High in dietary fiber and essential minerals. Wears a cute crown!",
    clue: "Glossy deep purple vegetable used in Maharashtrian Bharli Vangi.",
    audioText: "Brinjal. वांगी. Purple vegetable with a green crown.",
  },
  {
    key: "veg_cauliflower",
    name: "Cauliflower",
    marathi: "फ्लॉवर (Flower)",
    hindi: "फूलगोभी (Phoolgobhi)",
    icon: "🥦",
    image: "/assets/charts/veg_cauliflower.png",
    category: "leafy",
    benefit: "High in Vitamin C and fiber to keep tummy happy and light.",
    clue: "Looks like a beautiful ivory flower bouquet surrounded by green leaves.",
    audioText: "Cauliflower. फ्लॉवर. Looks like a flower bouquet.",
  },
  {
    key: "veg_cabbage",
    name: "Cabbage",
    marathi: "पत्ता कोबी (Kobi)",
    hindi: "पत्तागोभी (Pattagobhi)",
    icon: "🥗",
    image: "/assets/charts/veg_cabbage.png",
    category: "leafy",
    benefit: "Crisp natural hydration and fiber that cleanses the digestive tract.",
    clue: "Round ball of tightly packed crunchy leaves.",
    audioText: "Cabbage. पत्ता कोबी. Tightly packed green leaves.",
  },
  {
    key: "veg_ladyfinger",
    name: "Ladyfinger / Okra",
    marathi: "भेंडी (Bhendi)",
    hindi: "भिंडी (Bhindi)",
    icon: "🌱",
    image: "/assets/charts/veg_ladyfinger.png",
    category: "fruit",
    benefit: "Excellent for sharp memory, brain focus, and smooth digestion.",
    clue: "Slim green fingers with cute star-shaped seeds inside.",
    audioText: "Ladyfinger. भेंडी. Slim green pods with star seeds.",
  },
  {
    key: "veg_capsicum",
    name: "Capsicum",
    marathi: "शिमला मिरची (Shimla Mirchi)",
    hindi: "शिमला मिर्च (Shimla Mirch)",
    icon: "🫑",
    image: "/assets/charts/veg_capsicum.png",
    category: "fruit",
    benefit: "Vitamin A and C booster that guards against seasonal sniffles.",
    clue: "Crisp and juicy bell pepper that comes in green, red, and yellow.",
    audioText: "Capsicum. शिमला मिरची. Crunchy bell pepper.",
  },
  {
    key: "veg_cucumber",
    name: "Cucumber",
    marathi: "काकडी (Kaakdi)",
    hindi: "खीरा (Kheera)",
    icon: "🥒",
    image: "/assets/charts/veg_cucumber.png",
    category: "fruit",
    benefit: "95% cooling hydration that keeps kids fresh on hot sunny days.",
    clue: "Cool crunchy salad favorite with salt, pepper, and lemon juice.",
    audioText: "Cucumber. काकडी. Cool and refreshing hydrating vegetable.",
  },
  {
    key: "veg_pumpkin",
    name: "Pumpkin",
    marathi: "भोपळा (Bhopla)",
    hindi: "कद्दू (Kaddu)",
    icon: "🎃",
    image: "/assets/charts/veg_pumpkin.png",
    category: "fruit",
    benefit: "Full of beta-carotene, zinc, and gentle natural sweetness.",
    clue: "Big golden orange vegetable made into sweet Gharge and puris!",
    audioText: "Pumpkin. तांबडा भोपळा. Sweet golden vegetable.",
  },
  {
    key: "veg_beetroot",
    name: "Beetroot",
    marathi: "बीट (Beet)",
    hindi: "चुकंदर (Chukandar)",
    icon: "🍠",
    image: "/assets/charts/veg_beetroot.png",
    category: "root",
    benefit: "Boosts red blood cells and stamina for energetic playground play.",
    clue: "Deep ruby red root vegetable that turns your salad pink!",
    audioText: "Beetroot. बीट. Ruby red vegetable for healthy blood.",
  },
  {
    key: "veg_radish",
    name: "Radish",
    marathi: "मुळा (Mula)",
    hindi: "मूली (Mooli)",
    icon: "🪄",
    image: "/assets/charts/veg_radish.png",
    category: "root",
    benefit: "Purifies the stomach and aids healthy active liver function.",
    clue: "Crisp white root with a spicy zest in warm Mooli Parathas.",
    audioText: "Radish. मुळा. Crisp white zesty root vegetable.",
  },
  {
    key: "veg_corn",
    name: "Sweet Corn",
    marathi: "मका (Maka)",
    hindi: "भुट्टा (Bhutta)",
    icon: "🌽",
    image: "/assets/charts/veg_corn.png",
    category: "fruit",
    benefit: "Dietary fiber and lutein that fuels growing kids with sunshine energy.",
    clue: "Golden sweet kernels roasted warm with butter, salt, and lime.",
    audioText: "Sweet Corn. मका. Juicy golden yellow kernels.",
  },
  {
    key: "veg_ginger",
    name: "Ginger",
    marathi: "आले (Aale)",
    hindi: "अदरक (Adrak)",
    icon: "🫚",
    image: "/assets/charts/veg_ginger.png",
    category: "root",
    benefit: "Ayurvedic throat-soothing remedy that wards off coughs.",
    clue: "Knobby aromatic spice root used in hot tea and herbal soups.",
    audioText: "Ginger. आले. Healing aromatic root.",
  },
  {
    key: "veg_garlic",
    name: "Garlic",
    marathi: "लसूण (Lasun)",
    hindi: "लहसुन (Lahsun)",
    icon: "🧄",
    image: "/assets/charts/veg_garlic.png",
    category: "bulb",
    benefit: "Super immunity shield that keeps the heart and body resilient.",
    clue: "Papery white bulb with fragrant cloves that sizzle in tadka!",
    audioText: "Garlic. लसूण. Healthy aroma cloves.",
  },
  {
    key: "veg_bitter_gourd",
    name: "Bitter Gourd",
    marathi: "कारले (Karle)",
    hindi: "करेला (Karela)",
    icon: "🥒",
    image: "/assets/charts/veg_bitter_gourd.png",
    category: "fruit",
    benefit: "Bitter taste that supercharges gut health and blood purity.",
    clue: "Green bumpy gourd cooked with jaggery and spices for strength.",
    audioText: "Bitter Gourd. कारले. Bitter taste but super healthy cleanser.",
  },
  {
    key: "veg_bottle_gourd",
    name: "Bottle Gourd",
    marathi: "दुधी भोपळा (Dudhi)",
    hindi: "लौकी (Lauki)",
    icon: "🍈",
    image: "/assets/charts/veg_bottle_gourd.png",
    category: "fruit",
    benefit: "Gentle on the stomach and cooling for the whole body.",
    clue: "Smooth pale green gourd made into delicious sweet Dudhi Halwa.",
    audioText: "Bottle Gourd. दुधी भोपळा. Gentle cooling vegetable.",
  },
];

export const DEFAULT_BIRDS: VisualChartItem[] = [
  {
    key: "bird_peacock",
    name: "Peacock",
    marathi: "मोर (Mor)",
    hindi: "मोर (Mor)",
    icon: "🦚",
    image: "/assets/charts/bird_peacock.png",
    category: "garden",
    sound: "May-awe! (पिहू-पिहू)",
    fact: "National Bird of India! Spreads its iridescent royal blue feathers in the rain.",
    audioText: "Peacock. मोर. National Bird of India with gorgeous feathers.",
  },
  {
    key: "bird_parrot",
    name: "Parrot",
    marathi: "पोपट (Popat)",
    hindi: "तोता (Tota)",
    icon: "🦜",
    image: "/assets/charts/bird_parrot.png",
    category: "garden",
    sound: "Squawk! (मिठू-मिठू)",
    fact: "Vibrant green feathers, curved red beak, and can cleverly copy human speech.",
    audioText: "Parrot. पोपट. Green bird with a red beak that mimics speech.",
  },
  {
    key: "bird_sparrow",
    name: "Sparrow",
    marathi: "चिमणी (Chimni)",
    hindi: "गौरैया (Gauraiya)",
    icon: "🐤",
    image: "/assets/charts/bird_sparrow.png",
    category: "garden",
    sound: "Cheep Cheep! (चिव-चिव)",
    fact: "Cheerful little garden bird that hops on windowsills looking for seeds.",
    audioText: "Sparrow. चिमणी. Little cheerful garden bird that chirps.",
  },
  {
    key: "bird_pigeon",
    name: "Pigeon / Dove",
    marathi: "कबूतर (Kabootar)",
    hindi: "कबूतर (Kabootar)",
    icon: "🕊️",
    image: "/assets/charts/bird_pigeon.png",
    category: "garden",
    sound: "Coo Coo! (गुटरगूँ)",
    fact: "Universal messenger of peace with fantastic compass memory.",
    audioText: "Pigeon. कबूतर. Gentle bird symbol of peace.",
  },
  {
    key: "bird_crow",
    name: "Crow",
    marathi: "कावळा (Kaawla)",
    hindi: "कौआ (Kauva)",
    icon: "🐦‍⬛",
    image: "/assets/charts/bird_crow.png",
    category: "garden",
    sound: "Caw Caw! (काव-काव)",
    fact: "One of Earth's smartest animals! Can solve multi-step puzzles and use sticks.",
    audioText: "Crow. कावळा. Super smart black bird.",
  },
  {
    key: "bird_eagle",
    name: "Eagle",
    marathi: "गरुड (Garud)",
    hindi: "चील / गरुड़ (Garud)",
    icon: "🦅",
    image: "/assets/charts/bird_eagle.png",
    category: "wild",
    sound: "Screech! (किंचाळणे)",
    fact: "Lord of the skies! Razor-sharp eyesight can spot small mice from high above.",
    audioText: "Eagle. गरुड. Powerful flyer with sharp vision.",
  },
  {
    key: "bird_owl",
    name: "Owl",
    marathi: "घुबड (Ghubad)",
    hindi: "उल्लू (Ullu)",
    icon: "🦉",
    image: "/assets/charts/bird_owl.png",
    category: "wild",
    sound: "Hoot Hoot! (हूट-हूट)",
    fact: "Wise nocturnal bird with silent flying feathers and eyes that pierce the night.",
    audioText: "Owl. घुबड. Nocturnal bird that sees in the dark.",
  },
  {
    key: "bird_duck",
    name: "Duck",
    marathi: "बदक (Badak)",
    hindi: "बत्तख (Battakh)",
    icon: "🦆",
    image: "/assets/charts/bird_duck.png",
    category: "water",
    sound: "Quack Quack! (क्वॅक-क्वॅक)",
    fact: "Webbed paddle feet and waterproof feathers make it a natural pond swimmer.",
    audioText: "Duck. बदक. Duck says Quack Quack.",
  },
  {
    key: "bird_swan",
    name: "Swan",
    marathi: "हंस (Hansa)",
    hindi: "हंस (Hans)",
    icon: "🦢",
    image: "/assets/charts/bird_swan.png",
    category: "water",
    sound: "Honk! (मधुर आवाज)",
    fact: "Graceful white bird with a curved neck gliding smoothly on clear lakes.",
    audioText: "Swan. हंस. Graceful white water bird.",
  },
  {
    key: "bird_flamingo",
    name: "Flamingo",
    marathi: "रोहित पक्षी (Flamingo)",
    hindi: "राजहंस (Flamingo)",
    icon: "🦩",
    image: "/assets/charts/bird_flamingo.png",
    category: "water",
    sound: "Honk! (ध्वनी)",
    fact: "Gorgeous pink feathers and balance champion who sleeps standing on one leg!",
    audioText: "Flamingo. रोहित पक्षी. Beautiful pink bird that stands on one leg.",
  },
  {
    key: "bird_kingfisher",
    name: "Kingfisher",
    marathi: "खंड्या (Khandya)",
    hindi: "नीलकंठ (Kingfisher)",
    icon: "🐦",
    image: "/assets/charts/bird_kingfisher.png",
    category: "water",
    sound: "Whistle! (शिट्टी)",
    fact: "Dazzling turquoise feathers. Dives like a blue arrow into rivers for tiny fish.",
    audioText: "Kingfisher. खंड्या. Dazzling turquoise bird that dives for fish.",
  },
  {
    key: "bird_woodpecker",
    name: "Woodpecker",
    marathi: "सुतार पक्षी (Sutaar)",
    hindi: "कठफोड़वा (Kathphodwa)",
    icon: "🪶",
    image: "/assets/charts/bird_woodpecker.png",
    category: "wild",
    sound: "Tap-Tap-Tap! (टक-टक)",
    fact: "Taps tree bark like a carpenter with its strong beak to find insects.",
    audioText: "Woodpecker. सुतार पक्षी. Pecks tree bark to find insects.",
  },
  {
    key: "bird_hen",
    name: "Rooster & Hen",
    marathi: "कोंबडा (Kombda)",
    hindi: "मुर्गा (Murga)",
    icon: "🐓",
    image: "/assets/charts/bird_hen.png",
    category: "garden",
    sound: "Cock-a-doodle-doo! (कुकुच-कू)",
    fact: "Wakes the whole countryside at dawn with a cheerful morning crow.",
    audioText: "Rooster. कोंबडा. Rooster crows at dawn.",
  },
  {
    key: "bird_ostrich",
    name: "Ostrich",
    marathi: "शहामृग (Shahamrug)",
    hindi: "शुतुरमुर्ग (Shuturmurg)",
    icon: "🦤",
    image: "/assets/charts/bird_ostrich.png",
    category: "flightless",
    sound: "Boom! (गुंजण)",
    fact: "Heaviest bird on Earth! Cannot fly, but sprints faster than racehorses.",
    audioText: "Ostrich. शहामृग. The largest bird in the world.",
  },
  {
    key: "bird_penguin",
    name: "Penguin",
    marathi: "पेंग्विन (Penguin)",
    hindi: "पेंगुइन (Penguin)",
    icon: "🐧",
    image: "/assets/charts/bird_penguin.png",
    category: "flightless",
    sound: "Bray! (ध्वनी)",
    fact: "Waddles on Antarctic ice and zooms through freezing seas like a torpedo.",
    audioText: "Penguin. पेंग्विन. Waddles on snow and swims in chilly seas.",
  },
  {
    key: "bird_cuckoo",
    name: "Cuckoo / Koel",
    marathi: "कोकिळा (Kokila)",
    hindi: "कोयल (Koel)",
    icon: "🐤",
    image: "/assets/charts/bird_cuckoo.png",
    category: "garden",
    sound: "Koo-oo! (कुहू-कुहू)",
    fact: "Sings sweet soothing melodies in the spring among fragrant mango groves.",
    audioText: "Cuckoo. कोकिळा. Sings sweet melody in spring.",
  },
];

export const DEFAULT_EMOTIONS: VisualChartItem[] = [
  {
    key: "emotion_happy",
    name: "Happy",
    marathi: "आनंदी (Aanandi)",
    hindi: "खुश (Khush)",
    icon: "😊",
    image: "/assets/charts/emotion_happy.png",
    category: "positive",
    color: "#f59e0b",
    cue: "Big glowing smile, sparkling eyes, bouncing posture!",
    tool: "Share your joyful smile with a friend or family member!",
    audioText: "Happy. आनंदी. Feeling cheerful and full of bright joy.",
  },
  {
    key: "emotion_excited",
    name: "Excited",
    marathi: "उत्साही (Utsahi)",
    hindi: "उत्साहित (Utsahit)",
    icon: "🤩",
    image: "/assets/charts/emotion_excited.png",
    category: "positive",
    color: "#ea580c",
    cue: "Heart fluttering with joy, lots of energy to jump and cheer!",
    tool: "Channel that energy into drawing, dancing, or sharing stories!",
    audioText: "Excited. उत्साही. Bursting with fun energy and anticipation.",
  },
  {
    key: "emotion_proud",
    name: "Proud",
    marathi: "अभिमान (Abhimaan)",
    hindi: "गर्व (Garv)",
    icon: "🥳",
    image: "/assets/charts/emotion_proud.png",
    category: "positive",
    color: "#8b5cf6",
    cue: "Standing tall, warm heart, knowing you persevered and succeeded!",
    tool: "Give yourself a high five! You worked hard and learned something new!",
    audioText: "Proud. मला अभिमान वाटतो. Celebrate your effort and achievement.",
  },
  {
    key: "emotion_loved",
    name: "Loved & Cared For",
    marathi: "मायेची भावना (Maaya)",
    hindi: "प्यार (Pyaar)",
    icon: "🥰",
    image: "/assets/charts/emotion_loved.png",
    category: "positive",
    color: "#ec4899",
    cue: "Warm cozy feeling inside your chest, feeling safe and cherished.",
    tool: "Give a parent, teacher, friend, or pet a gentle warm hug.",
    audioText: "Loved. प्रेम आणि माया. Feeling safe, cherished, and warm.",
  },
  {
    key: "emotion_calm",
    name: "Calm & Peaceful",
    marathi: "शांत (Shaant)",
    hindi: "शांत (Shaant)",
    icon: "😌",
    image: "/assets/charts/emotion_calm.png",
    category: "calm",
    color: "#10b981",
    cue: "Slow steady breathing, relaxed shoulders, peaceful mind.",
    tool: "Close your eyes, feel the gentle breeze, and enjoy the stillness.",
    audioText: "Calm. शांत. Relaxed and peaceful like a quiet lake.",
  },
  {
    key: "emotion_curious",
    name: "Curious",
    marathi: "उत्सुक (Utsuk)",
    hindi: "जिज्ञासु (Jigyasu)",
    icon: "🧐",
    image: "/assets/charts/emotion_curious.png",
    category: "calm",
    color: "#0284c7",
    cue: "Tilted head, questioning look, eager to explore and learn!",
    tool: "Ask an interesting question like 'Why?' or 'How does that work?'",
    audioText: "Curious. उत्सुक. Ready to ask questions and discover the world.",
  },
  {
    key: "emotion_grateful",
    name: "Grateful & Thankful",
    marathi: "कृतज्ञ (Krutadnya)",
    hindi: "आभारी (Aabhari)",
    icon: "🙏",
    image: "/assets/charts/emotion_grateful.png",
    category: "positive",
    color: "#14b8a6",
    cue: "Appreciating the good people and blessings around you.",
    tool: "Say a sincere 'Thank You' to someone who helped you today.",
    audioText: "Grateful. कृतज्ञ. Saying thank you for the good things in life.",
  },
  {
    key: "emotion_brave",
    name: "Brave & Courageous",
    marathi: "शूर / धाडसी (Dhaadsi)",
    hindi: "बहादुर (Bahadur)",
    icon: "🦁",
    image: "/assets/charts/emotion_brave.png",
    category: "positive",
    color: "#d97706",
    cue: "Feeling nervous, but taking a brave breath and trying anyway!",
    tool: "Say to yourself: 'I am strong, I can try my best!'",
    audioText: "Brave. धाडसी. Taking courage to try even when things are new.",
  },
  {
    key: "emotion_sad",
    name: "Sad",
    marathi: "दुःखी (Dukkhi)",
    hindi: "उदास (Udas)",
    icon: "😢",
    image: "/assets/charts/emotion_sad.png",
    category: "big_feelings",
    color: "#3b82f6",
    cue: "Drooping mouth, heavy chest, teary eyes.",
    tool: "It's okay to cry. Talk to someone who cares, or cuddle a soft pillow.",
    audioText: "Sad. दुःखी. Sadness is normal. Talk to someone who loves you.",
  },
  {
    key: "emotion_angry",
    name: "Angry / Mad",
    marathi: "रागावलेला (Raagaavlela)",
    hindi: "गुस्सा (Gussa)",
    icon: "😠",
    image: "/assets/charts/emotion_angry.png",
    category: "big_feelings",
    color: "#ef4444",
    cue: "Clenched fists, warm cheeks, tense jaw, fast heartbeat.",
    tool: "Take 3 deep dinosaur breaths: breathe in slow, blow out like cooling soup.",
    audioText: "Angry. राग आला आहे. Stop and take three deep breaths to cool down.",
  },
  {
    key: "emotion_scared",
    name: "Scared / Afraid",
    marathi: "घाबरलेला (Ghaabarlela)",
    hindi: "डरा हुआ (Dara hua)",
    icon: "😨",
    image: "/assets/charts/emotion_scared.png",
    category: "big_feelings",
    color: "#7c3aed",
    cue: "Fast heartbeat, wide eyes, wanting to hide or find comfort.",
    tool: "Hold a grown-up's hand. Name 3 things you can see and touch.",
    audioText: "Scared. भीती वाटत आहे. You are safe. Hold a hand and take slow breaths.",
  },
  {
    key: "emotion_surprised",
    name: "Surprised",
    marathi: "चकित (Chakit)",
    hindi: "हैरान (Hairan)",
    icon: "😲",
    image: "/assets/charts/emotion_surprised.png",
    category: "calm",
    color: "#06b6d4",
    cue: "Raised eyebrows, wide open mouth, gasp of astonishment!",
    tool: "Take a second to process what happened: 'Wow! Look at that!'",
    audioText: "Surprised. चकित. Something unexpected and wondrous happened!",
  },
  {
    key: "emotion_confused",
    name: "Confused",
    marathi: "गोंधळलेला (Gondhal-lela)",
    hindi: "उलझन में (Uljhan)",
    icon: "🤔",
    image: "/assets/charts/emotion_confused.png",
    category: "calm",
    color: "#64748b",
    cue: "Scratched head, wrinkled brow, wondering what something means.",
    tool: "Raise your hand and ask: 'Could you please explain that again?'",
    audioText: "Confused. गोंधळ झाला आहे. It is great to ask questions to understand.",
  },
  {
    key: "emotion_tired",
    name: "Tired / Sleepy",
    marathi: "दमलेला (Thaklela)",
    hindi: "थका हुआ (Thaka hua)",
    icon: "🥱",
    image: "/assets/charts/emotion_tired.png",
    category: "calm",
    color: "#6b7280",
    cue: "Heavy eyelids, yawning, low energy after a busy active day.",
    tool: "Drink fresh water, rest your head, and enjoy a cozy nap or early bedtime.",
    audioText: "Tired. थकवा जाणवतो आहे. Time to rest and recharge your battery.",
  },
  {
    key: "emotion_shy",
    name: "Shy",
    marathi: "लाजाळू (Laajaalu)",
    hindi: "शर्मीला (Sharmila)",
    icon: "🥺",
    image: "/assets/charts/emotion_shy.png",
    category: "calm",
    color: "#a855f7",
    cue: "Hiding face slightly, soft voice, hesitant to step in front of crowd.",
    tool: "Take your time. A gentle wave or warm smile is a wonderful way to begin.",
    audioText: "Shy. लाजाळू. It is okay to take your time to warm up.",
  },
  {
    key: "emotion_frustrated",
    name: "Frustrated",
    marathi: "वैतागलेला (Vaitaglela)",
    hindi: "निराश (Niraash)",
    icon: "😤",
    image: "/assets/charts/emotion_frustrated.png",
    category: "big_feelings",
    color: "#f97316",
    cue: "Trying hard at a tough puzzle when things don't work immediately.",
    tool: "Take a 1-minute brain break. Remember: 'Mistakes help our brain grow!'",
    audioText: "Frustrated. वैताग आला आहे. Take a short pause. You will get it with practice!",
  },
];
